---
extends: default

rules:
  truthy: disable
  line-length:
    max: 200
    level: warning
  indentation: disable
  braces: disable
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
