---
- name: "Slurp the precedent configuration."
  become: yes
  ansible.builtin.slurp:
    src: "{{ teleport_config_path }}"
  register: old_conf_raw

- name: "Set the precedent configuration as a fact."
  ansible.builtin.set_fact:
    old_conf: "{{ old_conf_raw['content'] | b64decode | from_yaml }}"

- name: "Set fact teleport_auth_token from precedent configuration" # noqa no-handler
  ansible.builtin.set_fact:
    teleport_auth_token: "{{ old_conf.teleport.auth_token }}"
  when:
    - old_conf.teleport.auth_token | default('', true) | string | length > 0
    - teleport_auth_token | default('', true) | string | length == 0

- name: "Set fact teleport_ca_pin from precedent configuration"
  ansible.builtin.set_fact:
    teleport_ca_pin: "{{ old_conf.teleport.ca_pin }}"
  when:
    - old_conf.teleport.ca_pin | default('', true) | string | length > 0
    - teleport_ca_pin | default('', true) | string | length == 0

- name: "Flush the teleport database when the token or ca_pin has changed."
  vars:
    _old_auth_token: "{{ old_conf.teleport.auth_token | default('', true) | string }}"
    _new_auth_token: "{{ teleport_auth_token | default('', true) | string }}"
    _old_ca_pin: "{{ old_conf.teleport.ca_pin | default('', true) | string }}"
    _new_ca_pin: "{{ teleport_ca_pin | default('', true) | string }}"
  when: >-
    (_old_auth_token | length > 0 and _new_auth_token | length > 0 and _new_auth_token != _old_auth_token)
    or (_old_ca_pin | length > 0 and _new_ca_pin | length > 0 and _new_ca_pin != _old_ca_pin)
  notify: Reload_Teleport
  become: yes
  block:
    - name: "Stop teleport service if enabled"
      ansible.builtin.systemd:
        name: "teleport"
        state: "stopped"
      when:
        - not is_container

    - name: "Delete teleport sqlite file"
      ansible.builtin.file:
        path: "/var/lib/teleport/proc/sqlite.db"
        state: absent
