---

- name: Set fact is_container
  ansible.builtin.set_fact:
    is_container: true
  when: >
    (ansible_virtualization_type is defined and
      (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
    )

- name: "Lookup the cloud server version if none was provided"
  ansible.builtin.include_tasks: detect_cloud_version.yml
  when:
    - teleport_autodetect_version
    - not teleport_version | string

- name: "Check if a teleport configuration is present"
  ansible.builtin.stat:
    path: "{{ teleport_config_path }}"
  register:  teleport_config_file

- name: Get auth_token # noqa risky-shell-pipe
  become: yes
  ansible.builtin.shell:
    cmd: grep -i "auth_token:" {{ teleport_config_path }} | cut -d ':' -f 2 | tr -d ' "'
  args:
    removes: "{{ teleport_config_path }}"
  register: "auth_token"
  changed_when: false
  when: teleport_config_file.stat.exists

- name: Set teleport_auth_token # noqa no-handler
  ansible.builtin.set_fact:
    teleport_auth_token: "{{ auth_token.stdout }}"
  when: auth_token.changed

- name: Get ca_pin # noqa risky-shell-pipe
  become: yes
  ansible.builtin.shell:
    cmd: grep -i "ca_pin" {{ teleport_config_path }} | cut -d ':' -f 2,3 | tr -d ' "'
  args:
    removes: "{{ teleport_config_path }}"
  register: "ca_pin"
  changed_when: false
  when: teleport_config_file.stat.exists

- name: Set teleport_ca_pin # noqa no-handler
  ansible.builtin.set_fact:
    teleport_ca_pin: "{{ ca_pin.stdout }}"
  when: ca_pin.changed

- name: "Dispatch on installation method"
  ansible.builtin.include_tasks: "{{ 'install_via_' + teleport_install_method + '.yml' }}"

- name: Create teleport config
  become: yes
  ansible.builtin.template:
    src: "{{ teleport_config_template }}"
    dest: "{{ teleport_config_path }}"
    owner: "root"
    group: "root"
    mode: "0600"
    backup: "{{ backup_teleport_config }}"
  when: teleport_template_config
  notify: Reload_Teleport

- name: "Configure systemd service"
  ansible.builtin.include_tasks: "systemd.yml"
  when: teleport_control_systemd
