---
dependency:
  name: galaxy
  enabled: True
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:24.04}
    # env:
    #   http_proxy: ${http_proxy}
    #   https_proxy: ${https_proxy}
    #   no_proxy: ${no_proxy}
    groups:
      - teleportclients
provisioner:
  name: ansible
  inventory:
    group_vars:
      teleportclients:
        teleport_systemd_env_content: |
          HTTPS_PROXY=http://1.2.3.4:8080
        teleport_apps:
          - name: app-test
            uri: https://172.30.1.10:8080/ 
            insecure_skip_verify: true
            labels:
              lable-1: "example"
  config_options:
    defaults:
      verbosity: 2
scenario:
  name: default
verifier:
  name: ansible
