---
name: molecule_tests

on:
  push:
  pull_request:
  workflow_dispatch:
  #schedule: # run weekly, every monday 01:00
  #- cron: "0 1 * * 1"

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - molecule_distro: "rockylinux:9"
            experimental: false
          - molecule_distro: "rockylinux:8"
            experimental: false
          - molecule_distro: "ubuntu:22.04"
            experimental: false
          - molecule_distro: "ubuntu:24.04"
            experimental: false
          - molecule_distro: "debian:11"
            experimental: false
          - molecule_distro: "debian:12"
            experimental: false
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      MOLECULE_NO_LOG: "false"
      ANSIBLE_ROLE: mikroways.teleport

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.ANSIBLE_ROLE }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Environment
        run: |
          pwd
          env
          find -ls
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && pip install -r requirements.txt
        continue-on-error: true
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
